// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HeaderLocaleChanger: typeof import('./components/Header/LocaleChanger.vue')['default']
    HeaderNav: typeof import('./components/Header/Nav.vue')['default']
    HeaderThemeChanger: typeof import('./components/Header/ThemeChanger.vue')['default']
    IconsIconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconsIconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconsIconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconsIconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconsIconTooling: typeof import('./components/icons/IconTooling.vue')['default']
  }
}
